name: chat_application
description: "Chat Application Made With Firebase"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6


  #Below are our custom packages
  network_service:
    path: ./packages/network_service
  firebase_service:
    path: ./packages/firebase_service
  chat_module:
    path: ./packages/modules/chat
  admin_user:
    path: ./packages/modules/admin_user
  auth:
    path: ./packages/modules/auth

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

