// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return _web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      case TargetPlatform.macOS:
        return _macos;
      case TargetPlatform.windows:
        return _windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions _web = FirebaseOptions(
    apiKey: 'AIzaSyCOJ1tB5YhyGvtXrVk8W5RL8FLF2Mi3kXg',
    appId: '1:875676004794:web:11d7e185bf16f92a50ad83',
    messagingSenderId: '875676004794',
    projectId: 'chat-application-ffd8c',
    authDomain: 'chat-application-ffd8c.firebaseapp.com',
    storageBucket: 'chat-application-ffd8c.appspot.com',
    measurementId: 'G-HW5YGVTFBK',
  );

  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: 'AIzaSyBkx1pLn4lNGWBq5mL97ycb_rqtmAYbe1o',
    appId: '1:875676004794:android:1a5519edee68788450ad83',
    messagingSenderId: '875676004794',
    projectId: 'chat-application-ffd8c',
    storageBucket: 'chat-application-ffd8c.appspot.com',
  );

  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: 'AIzaSyAtNpVTyA4LiwEdGRsPogNEwgcpMGjmFyo',
    appId: '1:875676004794:ios:c7c30023b3e9b7c150ad83',
    messagingSenderId: '875676004794',
    projectId: 'chat-application-ffd8c',
    storageBucket: 'chat-application-ffd8c.appspot.com',
    iosBundleId: 'com.alok.chat.chatApplication',
  );

  static const FirebaseOptions _macos = FirebaseOptions(
    apiKey: 'AIzaSyAtNpVTyA4LiwEdGRsPogNEwgcpMGjmFyo',
    appId: '1:875676004794:ios:c7c30023b3e9b7c150ad83',
    messagingSenderId: '875676004794',
    projectId: 'chat-application-ffd8c',
    storageBucket: 'chat-application-ffd8c.appspot.com',
    iosBundleId: 'com.alok.chat.chatApplication',
  );

  static const FirebaseOptions _windows = FirebaseOptions(
    apiKey: 'AIzaSyCOJ1tB5YhyGvtXrVk8W5RL8FLF2Mi3kXg',
    appId: '1:875676004794:web:ca08f878905c4eeb50ad83',
    messagingSenderId: '875676004794',
    projectId: 'chat-application-ffd8c',
    authDomain: 'chat-application-ffd8c.firebaseapp.com',
    storageBucket: 'chat-application-ffd8c.appspot.com',
    measurementId: 'G-VVLCKG7LDV',
  );
}
